### ISSUE TITLE
Add disclaimer

### ISSUE THREAD

**Issue by engines-wafu** [gavinedwards/sqirm#1]
A basic disclaimer needs to be added to login.php.

**Comment by engines-wafu** [comment]
@KesoGirl9, please help!

**Comment by KesoGirl9** [comment]
[Disclaimer.txt](https://github.com/gavinedwards/sqirm/files/1989747/Disclaimer.txt)

**Comment by engines-wafu** [comment]
Okay, I can see the file now in the code 🥇
