### ISSUE TITLE
Logo needs to be added

### ISSUE THREAD

**Issue by engines-wafu** [gavinedwards/sqirm#21]

**Comment by engines-wafu** [comment]
Added to login.php.

**Comment by engines-wafu** [comment]
Added to welcome.php

**Comment by tjulises** [comment]
Hello @gavinedwards 

I see this is a relatively new project
I'd like to help delivering a new logo!!!
a simple and cleaner version could be more pleasent to the eye, dont you think?
let me know if you'd like one and I'll start working inmediately, thanks!!!

**Comment by gavinedwards** [comment]
Would love to see what you can come up with!
